/**
 * Main jQuery media file for the plugin.
 *
 * @since 1.0.0
 *
 * @package TGM New Media Plugin
 * @author  Thomas Griffin
 */
jQuery(document).ready(function($){
    // Bind to our click event in order to open up the new media experience.
    $(document).on('click.tgmOpenMediaManager', '.tgm-open-media', function(e){
        // Prevent the default action from occuring.
        e.preventDefault();

        // Set variable to grab input field for dynamic population.
        var input_field = $(this).prev();

        /**
         * The media frame doesn't exist let, so let's create it with some options.
         *
         * This options list is not exhaustive, so I encourage you to view the
         * wp-includes/js/media-views.js file to see some of the other default
         * options that can be utilized when creating your own custom media workflow.
         */
        tgm_media_frame = wp.media.frames.tgm_media_frame = wp.media({
            /**
             * We can pass in a custom class name to our frame, so we do
             * it here to provide some extra context for styling our
             * media workflow. This helps us to prevent overwriting styles
             * for other media workflows.
             */
            className: 'media-frame tgm-media-frame',

            /**
             * When creating a new media workflow, we are given two types
             * of frame workflows to chose from: 'select' or 'post'.
             *
             * The 'select' workflow is the default workflow, mainly beneficial
             * for uses outside of a post or post type experience where a post ID
             * is crucial.
             *
             * The 'post' workflow is tailored to screens where utilizing the
             * current post ID is critical.
             *
             * Since we only want to upload an image, let's go with the 'select'
             * frame option.
             */
            frame: 'select',

            /**
             * We can determine whether or not we want to allow users to be able
             * to upload multiple files at one time by setting this parameter to
             * true or false. It defaults to true, but we only want the user to
             * upload one file, so let's set it to false.
             */
            multiple: false,

            /**
             * We can set a custom title for our media workflow. I've localized
             * the script with the object 'tgm_nmp_media' that holds our
             * localized stuff and such. Let's populate the title with our custom
             * text.
             */
            title: 'Choose Image',

            /**
             * We can force what type of media to show when the user views his/her
             * library. Since we are uploading an image, let's limit the view to
             * images only.
             */
            library: {
                type: 'image'
            },

            /**
             * Let's customize the button text. It defaults to 'Select', but we
             * can customize it here to give us better context.
             *
             * We can also determine whether or not the modal requires a selection
             * before the button is enabled. It requires a selection by default,
             * and since this is the experience desired, let's keep it that way.
             *
             * By default, the toolbar generated by this frame fires a generic
             * 'select' event when the button is clicked. We could declare our
             * own events here, but the default event will work just fine.
             */
            button: {
                text:  'Select as Image'
            }
        });

        /**
         * ========================================================================
         * EVENT BINDING
         *
         * This section before opening the modal window should be used to bind to
         * any events where we want to customize the view. This includes binding
         * to any custom events that may have been generated by us creating
         * custom controller states and views.
         *
         * The events used below are not exhaustive, so I encourage you to again
         * study the wp-includes/js/media-views.js file for a better feel of all
         * the potential events you can attach to.
         * ========================================================================
         */

        /**
         * We are now attaching to the default 'select' event and grabbing our
         * selection data. Since the button requires a selection, we know that a
         * selection will be available when the event is fired.
         *
         * All we are doing is grabbing the current state of the frame (which will
         * be 'library' since that's the only area where we can make a selection),
         * getting the selection, calling the 'first' method to pluck the first
         * object from the string and then forcing a faux JSON representation of
         * the model.
         *
         * When all is said and done, we are given absolutely everything we need to
         * insert the data into our custom input field. Specifically, our
         * media_attachment object will hold a key titled 'url' that we want to use.
         */
        tgm_media_frame.on('select', function(){
            // Grab our attachment selection and construct a JSON representation of the model.
            var media_attachment = tgm_media_frame.state().get('selection').first().toJSON();

            // Send the attachment URL to our custom input field via jQuery.
            $(input_field).val(media_attachment.url);
        });

        // Now that everything has been set, let's open up the frame.
        tgm_media_frame.open();
    });

    // Remove images when clicked.
    $(document).on('click', '.tgm-remove-media', function(e){
    	e.preventDefault();
    	$(this).prev().prev().val('');
    });

    // Initialize sortable.
    var items = $('.tgm-repeatable-fields');
    items.sortable({
        containment: 'parent',
        cursor: 'move'
    });

    // Make repeatable fields for brand images.
    $(document).on('click', '.tgm-repeat-field', function(e){
    	e.preventDefault();
    	var $this     = $(this),
    	    parent    = $this.parent(),
    	    number    = $(parent).parent().find('.tgm-repeating-field:last').data('number'),
    	    column    = $(parent).data('column') ? true : false,
    	    new_field = column ? $(parent).html().split('data-number="' + number + '"').join('data-number="' + (number+1) + '"').split('_pressable_pricing[' + $(parent).data('number') + ']').join('_pressable_pricing[' + (number+1) + ']') : $(parent).html().split('data-number="' + number + '"').join('data-number="' + (number+1) + '"');

        console.log(new_field);

        $(new_field).find('input').val('');
        if ( column )
            $('<li class="tgm-repeating-field" data-number="' + (number+1) + '" data-column="true" style="margin-bottom:10px;border: 5px dashed #e5e5e5;padding:10px;cursor:move;">' + new_field + '</li>').insertAfter(parent);
        else
            $('<li class="tgm-repeating-field" data-number="' + (number+1) + '" data-column="false" style="margin-bottom:5px;">' + new_field + '</li>').insertAfter(parent);
    });

    // Remove field when clicked.
    $(document).on('click', '.tgm-remove-field', function(e){
    	e.preventDefault();
    	if ( $(this).parent().parent().find('.tgm-repeating-field').length <= 1 ) return;
    	$(this).parent().remove();
    });
});